// import {  Geist_Mono } from "next/font/google";
// import "./globals.css";
import { Inter } from "next/font/google";
import { Archivo_Black } from "next/font/google";
import "../styles/globals.css";
import "../styles/pstyle.css";
import "../styles/nstyle.css";
import 'primereact/resources/themes/lara-light-blue/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import Top from "./layout/top";
import Footer from "./layout/footer";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const archivoBlack = Archivo_Black({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-archivo-black",
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Redington AWS SMB Portal",
  description: "Generated by Redington AWS SMB Portal",
  icons: {
    icon: [{ url: "/images/favicon.svg" }],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${archivoBlack.variable} antialiased`} >
        <Top />
        <div className="mt-[40px] xl:mt-[50px] 2xl:mt-[56px] 3xl:mt-[3.021vw]">
          <main className="">{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
