
import { Inter } from "next/font/google";
import { Archivo_Black } from "next/font/google";
import "../styles/globals.css";
import "../styles/pstyle.css";
import "../styles/nstyle.css";
import 'primereact/resources/themes/lara-light-blue/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import LayoutClient from "./layout/layout";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const archivoBlack = Archivo_Black({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-archivo-black",
});

export const metadata = {
  title: "Redington AWS SMB Portal",
  description: "Generated by Redington AWS SMB Portal",
  icons: {
    icon: [{ url: "/images/favicon.svg" }],
  },
};

export default function RootLayout({ children }) {
  return (

     <html lang="en">
      <body className={`${inter.variable} ${archivoBlack.variable} antialiased`}>
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
