// import {  Geist_Mono } from "next/font/google";
// import "./globals.css";
import "../styles/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Redington AWS SMB Portal",
  description: "Generated by Redington AWS SMB Portal",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`} >
        {children}
      </body>
    </html>
  );
}
